version: "3.8"

services:
  db:
    image: postgres:16
    container_name: blogging_db
    restart: always
    environment:
      POSTGRES_DB: blogging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: blogging_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blogging
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: on-failure

volumes:
  pgdata:
